notifications:
  email:
    false

sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

install:
  - "pip install ."

script:
  - "python setup.py build"
  - "python setup.py test"

deploy:
  provider: pypi
  user: moxfyre
  password:
    secure: sI1GekmIIbq8bEwEf0w51sW9hgQCG6n7DFes0eR+z3emxOP/yO4vGZ9suWZRF+47mns5fq+tK0L2ZNyGRgmJRv66/erTudA7+299Yuev+Tw8JoPeJju/bARPMJ9/1pAWf+bSMg7zg7Gw3gkF8okTYEvfdFxU1X1HO+xIkzTZ5Hcu4+Vn8bhTX0omBluLrvjriHVOZN1NGoxoC4NX7gyXrI7dS+GTRuJP/Lv6yVzlBB/LGcP91Ym6beedN9NpWNL6IZC15pWCEruI+BZpIs/R0w+OqW68kavY/OSiS+Ly+p50YAVyWpYhGundkFQE5yYL1zUrzcsZAs2Xqw6zGlkE0oaMnPO1y3X4LhQqjbWrM8qnK70MHnQmTgAaHa5jIqKDB0i2mQCtuv9rIG3VcJNqO2jN3EO9YXafMtQfoOq9o0EcWHg4gRcE/N6GS8r6vLRD4RC3TZG9N9ToIQveyGucBgLSDGJApv5AwJMJm1GTKAoK9bVTelI/HytzdJDUATBE0bn/DzJorS5ubJFH/XITZYjPpVmuQ+gbEo66GGCSBHNaefAsSTWfOhdjkFr58Uegm41uI3WqJskG/9hXwK7VeNYV+JF80cwd+KAq9ffadCdbG1K7ZbYRXVdA6oNs1JGhM0LKUDBOx8EiwdMIHmlFtjc1DuD3awcHGiO43ri1a+Y=
  on:
    tags: true
    repo: dlenski/aztec_code_generator
